apiVersion: v1
kind: ConfigMap
metadata:
  name: env
  labels:
    app: {{ .Chart.Name }}
data:
  # Generate environment variables from the `values.yaml`
  .env: |
    {{- range $key, $value := .Values.env }}
    {{ $key }}={{ $value }}
    {{- end }}
