apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hoppscotch.fullname" . }}-env
  labels:
    app: {{ .Chart.Name }}
data:
  {{- range $key, $val := .Values.env }}
    {{ $key }}: "{{ $val }}"
  {{- end }}