{{- if .Values.kong.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ include "hoppscotch.fullname" . }}-gateway
spec:
  gatewayClassName: kong
  listeners:
  {{- range $index, $port := .Values.kong.externalPorts }}
  - name: proxy-{{ $index }}
    port: {{ $port }}
    protocol: HTTP
  {{- end }}
{{- end }}
