apiVersion: v1
kind: Service
metadata:
  name: {{ include "hoppscotch.fullname" . }}-service
  labels:
    {{- include "hoppscotch.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    # - port: 80
    #   targetPort: http
    #   protocol: TCP
    #   name: http
    - name: {{ include "hoppscotch.fullname" . }}-front
      port: 3000
      targetPort: front
      protocol: TCP
    - name: {{ include "hoppscotch.fullname" . }}-admin
      port: 3100
      targetPort: admin
      protocol: TCP
    - name: {{ include "hoppscotch.fullname" . }}-backend
      port: 3170
      targetPort: backend
      protocol: TCP
  selector:
    {{- include "hoppscotch.selectorLabels" . | nindent 4 }}
